title: Fake website
author: Alexander Supertramp
email: asupertramp@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Just a fun loving furry in a world full of e-boys 
  Not affiliated with Chris McCandles, just a fan really
  that's why I have the name uWu

# social links
twitter_username: aSupertramp # DO NOT include the @ character, or else the build will fail!
github_username:  superTrampBoi # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
